

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8000:80
        volumes:
            - .:/var/www/html
        environment:
            - APP_ENV=local
            - APP_KEY=base64:c+DP+lQ28Tu1uHTXeqfBLVXP4Cc3ie62PLRuW2LMiP0=
            - DB_HOST=127.0.0.1
            - DB_PORT=3306
            - DB_DATABASE=shopping_app
            - DB_USERNAME=root
            - DB_PASSWORD=

    db:
        image: mysql:8
        restart: always
        environment:
            MYSQL_DATABASE: shopping_app
            MYSQL_ROOT_PASSWORD: rath@2002
        volumes:
            - db-data:/var/lib/mysql
        ports:
            - "3307:3306"

volumes:
    db-data:
